[.big]
[.text-center]
.[underline]#**__Enedis Experience__**#

****

{empty} +

[discrete]
==== _Summary_
[underline]#Role#: Back End Developer +
[underline]#Company#: Enedis SA (Electricité de France) +
[underline]#Location#: Le Capitole (Nanterre, France) +
[underline]#Duration#: 10+ months (Mai 2019 - present)

{empty} +

[discrete]
==== __Technical Environment__ +
[underline]#Platforms#: Windows 10, Windows Server 2012 R2 +
[underline]#Frameworks#: .NET 4.0 +
[underline]#Languages#: C# 4.0, Python 3.5, DPL +
[underline]#Libraries#: NUnit, NSubstitute, NFluent, Sqlite, Parsimonious, Mermaid, ZeroMQ +
[underline]#Tools#: Visual Studio 2019, Rider, PyCharm, yEd, Notepad++, PowerFactory 2018

{empty} +

[discrete]
==== _Product_ +
[underline]#Description#: +
Enedis Erable-Talon is an in-house, N-Tier application framework used to compute various electrotechnical metrics of the french electrical grid, such as calculating the cost of new connections. +
[underline]#Responsibilities#: +
My team and I were responsible for developing and maintaining Erable-Talon on the one hand and providing it as a service to other teams, on the other hand, to enable them to create and execute independent electrotechnical workflows. +
[underline]#Key achievements#:  +
Re-worked one-handedly an entire tier (Tier 0), which greatly improved the performance, stability, and reliability of the entire system +
Wrote extensive documentation regarding ongoing integration/deployment practices +
Refactored the Communication Module, a critical part of the system acting as a mediator between other modules +
Created a code generation pipeline that takes functional specifications (written in mermaid as decision trees) and converts them into working C# code
****