[.big]
[.text-center]
.[underline]#**__Tricentis Experience__**#

****

{empty} +

[discrete]
==== _Summary_
[underline]#Role#: Full Stack Developer +
[underline]#Company#: Tricentis GmbH +
[underline]#Location#: Vienna International Centre (Vienna, Austria) +
[underline]#Duration#: 10 months (September 2017 - June 2018)

{empty} +

[discrete]
==== __Technical Environment__ +
[underline]#Platforms#: Windows 10, Azure +
[underline]#Frameworks#: .NET 4.7, Angular 6 +
[underline]#Languages#: C# 7.2, TypeScript 2.9 +
[underline]#Libraries#: NUnit, Moq, Cosmos DB, Sql Server +
[underline]#Tools#: Visual Studio 2017, Visual Studio Code, Robo 3T

{empty} +

[discrete]
==== _Product_ +
[underline]#Description#: +
Tricentis Tosca is a software testing tool that is used to automate end-to-end testing software applications +
[underline]#Responsibilities#: +
My team and I were responsible for maintaining "thick" Tosca (Client-Server Architecture) on the one hand, and developing "thin" Tosca (Microservice Architecture) on the other hand. Strong believers in the Agile Manifesto, my team and I quickly adhered to the DevSecOps mindset by pushing the adoption of tools such as Git and VSTS (Visual Studio Team Services, now Azure DevOps) on the one side, and promoting CI (Continuous Integration) & CD (Continuous Delivery) practices along with our own-flavored CT (Continuous Testing) process (which includes Security Testing) on the other side. +
[underline]#Key achievements#:  +
Added new features to the Cloud Portal (e.g. User & Project Management, User Profile Editor) +
Implemented Health Checks mechanisms to the microservices to augment Service Uptime +
Increased the ease of use the application by adding various application settings (e.g. automatic authentication token storage, file upload size limit)
****